name: Ahmad Sheikhzada
description: Physics Ph.D., Research Scientist

<!-- avatar: https://github.com/ahmadsheikhzada/ahmadsheikhzada.github.io/tree/master/images/my_image.jpg--/>

theme: jekyll-theme-cayman
